/** Public QueryHost package surface. Internal transports and safety primitives are not re-exported. */

export type {
  GameCapability,
  GameDefinition,
  GameProtocol,
  GameRegistry,
  SupportLevel,
} from "./contracts/registry.js";
export {
  canonicalGameId,
  GAME_ALIASES,
  GAME_IDS,
  GAME_REGISTRY,
  getGameDefinition,
  isGameAlias,
  isGameId,
  isGameInputId,
  listGames,
} from "./contracts/registry.js";
export type {
  CanonicalGameId,
  GameAlias,
  GameAliasMap,
  GameId,
  GameDataMap,
  GameInputId,
  GameProtocolMap,
  GameRawDataMap,
  QueryFailure,
  QueryInput,
  QueryManyEntry,
  QueryManyOptions,
  QueryResult,
  QuerySuccess,
} from "./contracts/query.js";
export { query, queryMany } from "./runtime/client.js";
export type {
  QueryError,
  QueryErrorCode,
  QueryMode,
  QuerySource,
  QuerySourceEvent,
  QuerySourceName,
  QuerySourceStatus,
  QueryWarning,
  QueryWarningCode,
  ServerInfo,
  ServerPlayers,
} from "./contracts/shared.js";
export type {
  A2sData,
  Arma3CreatorDlc,
  Arma3Data,
  Arma3Difficulty,
  Arma3Dlc,
  Arma3Mod,
  Arma3RawData,
  AmericanTruckSimulatorData,
  EuroTruckSimulator2Data,
  TheForestData,
  UnrealSessionData,
  UnrealSessionFlags,
  UnturnedData,
  UnturnedLink,
  EnshroudedData,
  InsurgencySandstormData,
  ArmaReforgerData,
  StarboundData,
  SpaceEngineersData,
  HumanitZData,
  VRisingData,
  EcoData,
  EcoRawData,
  VeinData,
  AvorionData,
  ArkSurvivalEvolvedData,
  ArkSurvivalEvolvedMod,
  ConanExilesData,
  KillingFloor2Data,
  DayOfDragonsData,
  SoulmaskData,
  SonsOfTheForestData,
  IcarusData,
  AbioticFactorData,
  A2sPlayer,
  A2sRawData,
  CfxData,
  CfxPlayer,
  CounterStrike2Data,
  CounterStrikeSourceData,
  DayZData,
  DayZMod,
  DayZRawData,
  DontStarveTogetherData,
  DontStarveTogetherPlayer,
  FiveMData,
  FiveMPlayer,
  GameRuleMap,
  GarrysModData,
  Left4DeadData,
  Left4Dead2Data,
  MinecraftBedrockData,
  MinecraftJavaData,
  MinecraftMotd,
  MinecraftPlugin,
  PalworldData,
  PalworldPlayer,
  MinecraftSoftware,
  MinecraftSrvTarget,
  ProjectZomboidData,
  ProjectZomboidPlayer,
  RedMData,
  RedMPlayer,
  RustData,
  RustPlayer,
  SevenDaysToDieData,
  SevenDaysToDiePlayer,
  SatisfactoryData,
  SatisfactoryHealth,
  SatisfactoryRawData,
  SatisfactoryServerState,
  SatisfactorySubState,
  SteamA2sData,
  SteamA2sPlayer,
  SourceTvEndpoint,
  TeamFortress2Data,
  TeamFortress2GameMode,
  VintageStoryData,
  ValheimData,
  ValheimPlayer,
} from "./contracts/games.js";
